version: '3.8'

services:
  r2r-server:
    image: sciphiai/r2r:latest
    container_name: r2r-server
    environment:
      - R2R_POSTGRES_USER=admin
      - R2R_POSTGRES_PASSWORD=admin
      - R2R_POSTGRES_HOST=postgres
      - R2R_POSTGRES_PORT=5432
      - R2R_POSTGRES_DBNAME=r2rdb
      - R2R_PROJECT_NAME=r2r
      - R2R_CONFIG_PATH=/app/user_configs/ollama.conf
      - OLLAMA_API_BASE=http://ollama:11434
    ports:
      - "8000:8000"
    volumes:
      - ./volumes/r2r:/app/user_configs
    depends_on:
      - postgres
      - ollama
    restart: always

  postgres:
    image: ankane/pgvector:latest
    container_name: r2r-postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=r2rdb
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always

  r2r-dashboard:
    image: sciphiai/r2r-dashboard:latest
    container_name: r2r-dashboard
    environment:
      - NEXT_PUBLIC_R2R_DEPLOYMENT_URL=http://r2r-server:8000
    ports:
      - "7273:3000"
    depends_on:
      - r2r-server
    restart: always

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./volumes/ollama_data:/root/.ollama
    restart: always

volumes:
  pgdata:

