version: '3.8'

services:
  r2r-server:
    image: sciphiai/r2r:latest
    container_name: r2r-server
    environment:
      - R2R_POSTGRES_USER=${R2R_POSTGRES_USER}
      - R2R_POSTGRES_PASSWORD=${R2R_POSTGRES_PASSWORD}
      - R2R_POSTGRES_HOST=postgres
      - R2R_POSTGRES_PORT=5432
      - R2R_POSTGRES_DBNAME=${R2R_POSTGRES_DBNAME}
      - R2R_PROJECT_NAME=${R2R_PROJECT_NAME}
      - R2R_CONFIG_PATH=${R2R_CONFIG_PATH}
      - OLLAMA_API_BASE=${OLLAMA_API_BASE}
    ports:
      - "8000:8000"
    volumes:
      - ./volumes/r2r:/app/user_configs
    depends_on:
      - postgres
    restart: always

  postgres:
    image: ankane/pgvector:latest
    container_name: r2r-postgres
    environment:
      - POSTGRES_USER=${R2R_POSTGRES_USER}
      - POSTGRES_PASSWORD=${R2R_POSTGRES_PASSWORD}
      - POSTGRES_DB=${R2R_POSTGRES_DBNAME}
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always

  r2r-dashboard:
    image: sciphiai/r2r-dashboard:latest
    container_name: r2r-dashboard
    environment:
      - NEXT_PUBLIC_R2R_DEPLOYMENT_URL=http://r2r-server:8000
    ports:
      - "7273:3000"
    depends_on:
      - r2r-server
    restart: always

volumes:
  pgdata:

